version: 0.1

environment_variables:
    plaintext:
        AWS_REGION: "us-west-2"
        IMAGE_REPO_NAME: "duclos-app/similarity-service"
        IMAGE_TAG: "test"

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --region $AWS_REGION)
    build:
        commands:
            - echo Building similarity-service
            - cd microservices/similarity_service
            - echo Build started on `date`
            - echo Building the Docker image...          
            - docker build -t $IMAGE_REPO_NAME .
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG